# Site settings
title: Causa Research
tagline: Policy is alpha
author: 
first_button_text: 'The Multibagger'
first_button_url: '#about'
header_img: /img/header.jpg
home_menu_text: Causa Research
description: Causa Research provides independent insight at the intersection of policy, geopolitics, and markets.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Theme customization
primary: '#005555'
dark: '#222'

# Contact details
email: 
telephone_number: 
whatsapp_number: 
twitter_username: 
github_username: volny
instagram_username: 
facebook_username: 
linkedin_username: 

# Data collections
collections:
  blocks:
    output: false
  gallery:
    output: false

# Build settings
markdown: kramdown

exclude:
  - serve
  - README.md
  - LICENCE

